# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SPpROB9b2bwGSSdKVPiBwmntb6PjSAYy
"""

from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_circles
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
X, y = make_circles(n_samples=1000, noise=0.05)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)
sns.scatterplot(x=X_train[:, 0], y=X_train[:, 1], hue=y_train)
plt.title("Train Data")
plt.show()